### ISSUE TITLE
Ignore gems whose name contain -

### ISSUE THREAD

**Issue by jmgarnier** [pheen/fuzzy_ruby_server#3]
Thank you for your awesome project!

See https://github.com/Shopify/ruby-lsp/issues/199#issuecomment-1550187025

> Unfortunately, I have more pressing side-projects and likely won't have time to work on this anymore.

Would you accept a small donation to fix that issue 😄 ?

**Comment by pheen** [comment]
Hey @jmgarnier ! New features, probably not unfortunately. Adding support for name-spacing Constant references is something I will likely add a some point though. There are a few other heuristics that don't work 100% of the time that could be useful like number of arguments and class name for a class method call on a constant.

- [ ] Parsing the gemfile incorrectly is just silly though so definitely happy to fix that 😅 

It's tough, Ruby is an awesome language and I would like to help build tooling to help the community as it's really needed for larger Ruby apps. For an effective LSP, what's needed is types in the source code. I don't believe large Ruby apps, much less the wider Ruby eco-system, will ever have decent type coverage. Gradual typing is simply frustrating in that case because I imagine most of the time when you ask the LSP for a reference the type won't be available anyways.

I think there is a choice right now. Large companies can stick with Ruby and either accept they will constantly have `NoMethodErrors` in Production, or be willing to pay for what I would guess is a shrinking pool of experienced Ruby devs that can avoid that. They could attempt to bushwhack their way out of `nil` issues through Sorbet/RSB, though is that effort worth it when you could move to a more modern language that will be a better developer experience and is a fraction of the infrastructure cost for the same level of performance.

Clearly these companies shouldn't just rewrite their core product, but making a plan to transition over the next few years is probably a great idea. I really wish a language existed for that niche I could recommend, essentially something with the simplicity of Ruby and the correctness of Rust. I don't think Go, Crystal, Elixir, or Rust its self fills that niche. I'm not aware of any languages that do, so I feel compelled to attempt to build one. My effort is currently going towards building that language, which is likely unrealistic but damn am I learning a lot!

**Comment by jmgarnier** [comment]
Thanks for the long and detailed reply 😄 

> Parsing the gemfile incorrectly is just silly though so definitely happy to fix that

May I help maybe? I have no experience in Rust but it does not sound too challenging?

**Comment by jmgarnier** [comment]
I am about to switch to IntelliJ which has this as a built in feature so closing that issue

**Comment by pheen** [comment]
That's probably a good call. I would be using RubyMine if it had the level of customization I like.

In any case, it turned out the issue was caused by [Rust requiring `-` to be escaped](https://github.com/pheen/fuzzy_ruby_server/commit/965a0a446e6045cbd02d29d36bbf15d00955275e#diff-dc2852d4c0a9a6f148427cb8de2d4e77bee220c26f5cf1872ea17a574deae1d9R431). Thanks again for reporting the issue!
