### ISSUE TITLE
Very high memory usage

### ISSUE THREAD

**Issue by jaydattc** [pheen/fuzzy_ruby_server#4]
Currently Fuzzy takes up almost all of my memory in Ubuntu 22.04.1.
Maybe some of the hash maps can be shifted to a file-based memory like sqlite instead of memory.

**Comment by pheen** [comment]
Hey @jaydattc , thanks for trying it out! https://github.com/quickwit-oss/tantivy is used for the search index. It does have support for using mmap. The in-memory store is currently [initialized here](https://github.com/pheen/fuzzy_ruby_server/blob/master/src/persistence.rs#LL293C13-L293C74). A config option could be added so instead it calls [create_from_tempdir](https://docs.rs/tantivy/latest/tantivy/struct.Index.html#method.create_from_tempdir).

A tempdir needs to be used because indexing on startup is still required, otherwise more work is needed to track changes made to files while the language server isn't running. For example, if a git branch is changed.

There should also be a config option to disable indexing gems as well. I've seen dependencies take up 3/4+ of the index, and while it's nice to be able to jump into those too if memory is at a premium then the ability to disable that could help here.

I can do that probably this weekend. If anyone wants to toss a PR for one or both in the meantime feel free.

- [ ] add a config option for `create_from_tempdir` instead of `create_in_ram`
- [ ] add a config option to disable indexing gems
- [ ] update documentation

**Comment by pheen** [comment]
It turns out using an mmap'ed index performs amazingly well. I also made some changes to how gems are indexed. With both of those changes a large Ruby app that would  take multiple GBs to index now takes as little as ~200mb of memory given some time after indexing, with a virtual memory size of ~1.5gb. The search performance still seems great.

Sorry it took while!
