### ISSUE TITLE
Support Additional Index Paths

### ISSUE THREAD

**Issue by megafloras** [pheen/fuzzy_ruby_server#7]
Hi there,

Fantastic work on implementing a _very_ fast Ruby LSP, especially as what appears to be a side-project. Rust and Ruby leads to great things it seems!

The only thing fully stopping me from switching over is the ability to utilize additional Indexing Paths. My company's projects do not use standard Gems for distributing dependencies, and instead uses its own build and dependency resolution system. As such, the only LSP we've successfully integrated with is Solargraph, via it's `include:` configuration in `.solargraph.yml`

> **include**
A list of directory globs to include in Solargraph’s code maps. The default configuration includes all .rb files in the folder.

Would it be reasonable or even possible for fuzzy to implement a similar feature, configured at either the package or Workspace Level? We primarily use VSCode, but have some Neovim and Eglot/lsp-mode folks around as well.

**Comment by pheen** [comment]
Thanks so much @megafloras ! 😃 

I added a config option `includeDirs`. It's formatted like: `[{ path: "/absolute/path", interface_only: false }]`. `interface_only` defaults to `true`.

It's formatted a little funny because normally only classes and methods are indexed for gems to save on indexing time and memory. If you would like to also index local variables and such set `interface_only: false`.

For VSCode, add to `settings.json` or whichever one you prefer if you wanted to config per workspace:

```
  "fuzzyRubyServer.includeDirs": [
    { "path": "/absolute/path", "interface_only": false }
  ]
```

Neovim users should be able to pass in the config with the same format, I think it's formatted like, not 100%:

```
config.fuzzy_ls.setup({
  init_options = {
    allocationType = "tempdir",
    indexGems = false,
    reportDiagnostics = true,
    includeDirs = {
      {
        path = "/absolute/path",
        interface_only = false
      }
    },
  },
})
```

I published `v0.7.5` so VSCode users can update the extension from the marketplace. Let me know what you think!

**Comment by megafloras** [comment]
Hi Pheen, this is fantastic so far! Testing in VSCode, it appears that it's working great out of the box! Very nice!

It looks like specifically it requires the absolute path, which can definitely work if necessary! However, I was curious if there was a possibility for utilizing relative paths?

By defualt, our Solargraph setups use configurations like the following:

```
include:
- lib/company/package/actions/**/*.rb
- ../different_package/lib/company/package/**/*.rb
- ../../.external_deps/external_apackage/Ruby/farm/ruby2.7.x/lib/ruby/**/*.rb
```

I know relative paths and symlinks are VERY strange in VScode at times, so if that's not a possibility I totally get it.

**Comment by pheen** [comment]
👋 Hey @megafloras , you had mentioned relative paths. Sorry for the wait!

The next version, `0.7.6` will be published soon and will have support for relative paths for `includeDirs`. Added [here](https://github.com/pheen/fuzzy_ruby_server/commit/40bc89f3778b6c463404e0674572bbef3abb2054).
